services:
    db:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: db
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql # Persist data to a named volume

    adminer:
      image: adminer
      ports:
        - "8000:8080"

volumes:
  db_data: