services:
  db:
    # image: postgres:latest
    image: postgres:16.6-bullseye
    # image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    attach: false

  adminer:
    image: adminer
    ports:
      - 8000:8080
    attach: false

volumes:
  postgres_data:
