services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=admin'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin@admin'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mysql
